//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ArmyConf.proto
namespace Config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArmyConf")]
  public partial class ArmyConf : global::ProtoBuf.IExtensible
  {
    public ArmyConf() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _Hp = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int Hp
    {
      get { return _Hp; }
      set { _Hp = value; }
    }
    private string _ResPath = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ResPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ResPath
    {
      get { return _ResPath; }
      set { _ResPath = value; }
    }
    private string _BT = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"BT", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string BT
    {
      get { return _BT; }
      set { _BT = value; }
    }
    private int _AtkRange = (int)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"AtkRange", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int AtkRange
    {
      get { return _AtkRange; }
      set { _AtkRange = value; }
    }
    private int _WaringRange = (int)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"WaringRange", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int WaringRange
    {
      get { return _WaringRange; }
      set { _WaringRange = value; }
    }
    private string _str = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"str", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string str
    {
      get { return _str; }
      set { _str = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArmyConf_ARRAY")]
  public partial class ArmyConf_ARRAY : global::ProtoBuf.IExtensible
  {
    public ArmyConf_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<Config.ArmyConf> _items = new global::System.Collections.Generic.List<Config.ArmyConf>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Config.ArmyConf> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}